### get product input from the user and then store it in somewhere then apply filter on the price

In [40]:
import pandas as pd
import numpy as np

In [41]:
import random

In [42]:
# 1 firset we create the empty list to store the user data
Product_Name = ["TV","Phone","Tab","PC"]
n=5
products = pd.DataFrame({
    "Product_ID" : range(1,6),
    "Product" : np.random.choice(Product_Name,n),
    # "Product" : np.random.choice(["TV","Phone","Tab","PC"],n),
    "Price" : np.random.randint(15000,100000,n),
    "Unit" : np.random.randint(15,50,n)
})

In [43]:
products

   Product_ID Product  Price  Unit
0           1   Phone  70765    44
1           2     Tab  28206    25
2           3   Phone  72908    44
3           4      PC  40083    43
4           5      PC  61201    20

In [44]:
df = pd.DataFrame(products)

In [45]:
df

   Product_ID Product  Price  Unit
0           1   Phone  70765    44
1           2     Tab  28206    25
2           3   Phone  72908    44
3           4      PC  40083    43
4           5      PC  61201    20

In [46]:
df["price"] = pd.to_numeric(df["Price"])
df["Unit"] = pd.to_numeric(df["Unit"])

In [47]:
dff = df[(df["price"] > 50000) ]
print("Proucts whose price greater than 40000 : \n",dff)

Proucts whose price greater than 40000 :
    Product_ID Product  Price  Unit  price
0           1   Phone  70765    44  70765
2           3   Phone  72908    44  72908
4           5      PC  61201    20  61201

In [48]:
print("The products whose quantity is even are  \n" ,df[df["Unit"] % 2 == 0])

The products whose quantity is even are
    Product_ID Product  Price  Unit  price
0           1   Phone  70765    44  70765
2           3   Phone  72908    44  72908
4           5      PC  61201    20  61201

get the input from user (product,quantity,price)
store in to the list
convert it into the dataframe using the pandas
apply the filter
but to fiter the numerical data we need to convert that particular column into numeric to perform numpy operations
so convert it into numeric
here we have to extract the product that has price > 40000
condition products["price"] > 40000
even condition = products["units"] % 2 == 0

In [53]:
n= 50
product = {"TV":80000,"Phone":50000,"Tab":25000,"LapToop":65000}
pro = np.random.choice(list(product),n)
df =  pd.DataFrame({
    "Product_ID" : np.arange(1,1+n),
    "Product" : pro,
    "price" : [product[p] for p in pro],
    "Qty" : np.random.randint(15,60,n)
})

In [54]:
df

    Product_ID  Product  price  Qty
0            1  LapToop  65000   38
1            2      Tab  25000   35
2            3       TV  80000   17
3            4       TV  80000   39
4            5      Tab  25000   27
5            6      Tab  25000   48
6            7  LapToop  65000   48
7            8    Phone  50000   38
8            9    Phone  50000   20
9           10  LapToop  65000   55
10          11    Phone  50000   34
11          12  LapToop  65000   47
12          13       TV  80000   50
13          14    Phone  50000   45
14          15  LapToop  65000   50
15          16      Tab  25000   50
16          17  LapToop  65000   56
17          18    Phone  50000   56
18          19      Tab  25000   49
19          20  LapToop  65000   53
20          21    Phone  50000   21
21          22    Phone  50000   37
22          23    Phone  50000   29
23          24      Tab  25000   58
24          25      Tab  25000   21
25          26      Tab  25000   36
26          27    Phone  50000   24
27          28  LapToop  65000   46
28          29      Tab  25000   58
29          30      Tab  25000   49
30          31      Tab  25000   29
31          32       TV  80000   37
32          33       TV  80000   46
33          34      Tab  25000   40
34          35       TV  80000   21
35          36       TV  80000   54
36          37  LapToop  65000   59
37          38      Tab  25000   51
38          39      Tab  25000   55
39          40      Tab  25000   55
40          41    Phone  50000   19
41          42    Phone  50000   55
42          43      Tab  25000   50
43          44  LapToop  65000   37
44          45  LapToop  65000   55
45          46    Phone  50000   41
46          47      Tab  25000   30
47          48  LapToop  65000   43
48          49  LapToop  65000   22
49          50    Phone  50000   33

In [58]:
df[(df["price"]>50000) and  (df["Product_ID"]%2==0)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().